---
title: "Travis CI"
description: |
  How to build R packages more efficiently with __Travis Continuos Integration__ service 
author:
  - name: Andrea Spano 
    affiliation: Quantide
    affiliation_url: http://www.quantide.com
date: "`r Sys.Date()`"
draft: true
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

__Travis CI__: <https://travis-ci.org/> is a  continuous integration service used to build and test software projects hosted on, but not only, GitHub.


Continuous integration (CI) is a practice where a team of developers integrate their code early and often to the main branch or code repository. The goal is to reduce the risk of seeing “integration hell” by waiting for the end of a project or a sprint to merge the work of all developers.

One of the primary benefits of adopting CI is that it will save you time during your development cycle by identifying and addressing conflicts early. It’s also a great way to reduce the amount of time spent on fixing bugs and regression by putting more emphasis on having a good test suite. Finally, it helps share a better understanding of the codebase and the features that you’re developing for your customers.

The first step on your journey to continuous integration: setting up automated testing.



